export const CONTENT_CATEGORIES = [
  {
    key: 'banner',
    label: 'Banner',
    aspectRatio: '16 / 6',
    aspectLabel: '16:6 (Lebar, seperti gambar sampul)',
  },
  {
    key: 'prestasi',
    label: 'Prestasi',
    hasDescription: true,
    titleLabel: 'Nama Prestasi',
    descriptionLabel: 'Keterangan Prestasi',
    aspectRatio: '4 / 3',
    aspectLabel: '4:3 (Landscape standar)',
  },
  {
    key: 'fasilitas',
    label: 'Fasilitas',
    hasDescription: true,
    titleLabel: 'Nama Fasilitas',
    descriptionLabel: 'Deskripsi Singkat',
    aspectRatio: '16 / 9',
    aspectLabel: '16:9 (Lebar). Foto terbaru akan tampil lebih besar di beranda.',
  },
  {
    key: 'kegiatan_unggulan',
    label: 'Kegiatan Unggulan',
    hasDescription: false,
    titleLabel: 'Nama Kegiatan',
    aspectRatio: '4 / 3',
    aspectLabel: '4:3 (Landscape standar)',
  },
  {
    key: 'pengurus_yayasan',
    label: 'Pengurus Yayasan',
    hasDescription: true,
    titleLabel: 'Nama',
    descriptionLabel: 'Jabatan',
    aspectRatio: '3 / 4',
    aspectLabel: '3:4 (Potret, seperti pas foto)',
  },
  {
    key: 'guru',
    label: 'Guru',
    hasDescription: true,
    titleLabel: 'Nama Guru',
    descriptionLabel: 'Mata Pelajaran / Jabatan',
    aspectRatio: '3 / 4',
    aspectLabel: '3:4 (Potret, seperti pas foto)',
  },
  {
  key: 'popup',
  label: 'Popup Iklan',
  hasDescription: false,
  hasRedirect: true,
  titleLabel: 'Judul Popup (opsional, untuk catatan internal)',
  aspectRatio: '3 / 4',
  aspectLabel: '3:4 (Potret). Muncul sebagai popup saat pengunjung membuka situs.',
},
];